##############################################################
# Rename the file extension to "._yaml" (remove "_") to enable
##############################################################

name:  Build Stochastic_Physics Unit Test Images (Docker) 

on:
  # run it on push to the default repository branch
  push:
    branches: [feature/dockerfile]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Stochastic_Physics Unit Test Image .......
    steps:
      - uses: actions/checkout@v2          
      - name: docker build stochastic_physics unit test image
        run: | 
         echo "docker build stochastic_physics unit test image"
         docker volume rm -f DataVolume
         docker run -d --rm -v DataVolume:/tmp ufscommunity/input-data:stochastic
         docker build -t stochastic_physics_test -f ./unit_tests/Dockerfile .
         docker run --rm -w "/home/builder/stochastic_physics/unit_tests" -v DataVolume:/home/builder/stochastic_physics/unit_tests -i --shm-size=1gb stochastic_physics_test 


