##############################################################
# Rename the file extension to "._yaml" (remove "_") to enable
##############################################################

name:  Build and Run Docker Stochastic_Physics Unit Test Image 

on:
  # run it on push to the default repository branch
  push:
    branches: [feature/dockerfile]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Stochastic_Physics Unit Test .......
    steps:
      - uses: actions/checkout@v3        
      - name: docker base image build
        run: | 
         echo "docker base image build"
         docker build -t stochastic_physics_test --no-cache --compress -f ./unit_tests/Dockerfile .
      - name: Prepare docker input data volume
        run: | 
         echo "Prepare docker input data volume"
         docker volume rm -f DataVolume
         docker run -d --rm -v DataVolume:/tmp ufscommunity/input-data:stochastic
      - name: Run docker stochastic_physics unit test
        run: | 
         echo "Run docker stochastic_physics unit test"      
         docker run --rm -v DataVolume:/tmp -i --shm-size=1gb stochastic_physics_test

